
services:

  # --- HDFS ---
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: unless-stopped
    ports:
      - "9871:9870"
      - "9001:9000"
    environment:
      - CLUSTER_NAME=bigdata-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode_data:/hadoop/dfs/name  # <--- Volume persistente
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: unless-stopped
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - datanode_data:/hadoop/dfs/data  # <--- Volume persistente
    networks:
      - bigdata-net
  # --- Fim HDFS ---

  meu_flume:
    image: bigdata-flume:latest
    build: .
    container_name: flume_semana1
    depends_on:
      - namenode
    volumes:
      - ./eventos.log:/dados/eventos.log
      - ./flume.conf:/dados/flume.conf
      - ./dados_saida:/dados_saida
    command: >
      flume-ng agent
      -n a1
      -c /opt/flume/conf
      -f /dados/flume.conf
      -Dflume.root.logger=INFO,console
    networks:
      - bigdata-net

  flink-jobmanager:
    build:
      context: ./flink
    image: meu-flink-python:1.18
    container_name: flink_jobmanager
    ports:
      - "8082:8081"
    command: jobmanager
    volumes:
      - ./flink:/opt/flink/job
      - ./dados_saida:/dados_saida
      - ./eventos.log:/dados/eventos.log
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - bigdata-net

  flink-taskmanager:
    build:
      context: ./flink
    image: meu-flink-python:1.18
    container_name: flink_taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - ./flink:/opt/flink/job
      - ./dados_saida:/dados_saida
      - ./eventos.log:/dados/eventos.log
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - bigdata-net

  spark:
    image: apache/spark:3.5.1-python3
    container_name: spark
    hostname: spark
    depends_on:
      - namenode
      - datanode
    environment:
      - PATH=/opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SPARK_HOME=/opt/spark
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./dados_saida:/dados_saida
    command: >
      /bin/bash -c "sleep infinity"
    networks:
      - bigdata-net
  
  # --- HBase ---
  hbase:
    image: dajobe/hbase
    container_name: hbase
    hostname: hbase-docker
    extra_hosts:
      - "hbase-docker:127.0.0.1"
      - "hbase:127.0.0.1"
    command: >
      /bin/bash -c "start-hbase.sh && hbase thrift start"
    ports:
      - "16011:16010"
      - "2182:2181"
      - "9091:9090"
    networks:
      bigdata-net:
        aliases:
          - hbase
          - hbase-docker
  
  # --- Hive ---
  hive:
    image: apache/hive:4.0.0
    container_name: hive
    hostname: hive
    depends_on:
      - namenode
      - datanode
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      - SERVICE_NAME=hiveserver2
      - FS_DEFAULT_NAME=hdfs://namenode:9000
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge

volumes:
  namenode_data:
  datanode_data: