a1.sources = origem1
a1.sinks = destino1
a1.channels = canal1


a1.sources.origem1.type = exec
a1.sources.origem1.command = tail -F /dados/eventos.log


a1.sinks.destino1.type = file_roll
a1.sinks.destino1.sink.directory = /dados_saida


a1.channels.canal1.type = memory
a1.channels.canal1.capacity = 1000
a1.channels.canal1.transactionCapacity = 100


a1.sources.origem1.channels = canal1
a1.sinks.destino1.channel = canal1